version: "3.7"

services:
  agent:
    build:
      context: ../
      dockerfile: "./deployments/Dockerfile"
      target: developer
    environment:
      DEBUG_API_USER: "admin"
      DEBUG_API_PASSWORD: "password123"
      DEBUG_API_ADDR: "0.0.0.0:8080"
    ports:
      - "127.0.0.1:8080:8080"
  c2:
    build:
      context: ../
      dockerfile: "./deployments/c2.Dockerfile"
      target: production
    ports:
      - "127.0.0.1:8080:8080"