version: "3.7"

services:
  agent:
    build:
      context: ./
      target: developer
    environment:
      DEBUG_API_USERNAME: "admin"
      DEBUG_API_PASSWORD: "password123"
      DEBUG_API_ADDR: "0.0.0.0:8080"
    ports:
      - "127.0.0.1:8080:8080"