version: "3.7"

services:
  agent:
    build:
      context: ../
      dockerfile: "./docker/agent.Dockerfile"
      target: dev
    environment:
      C2_HTTP_ADDR: http://paragon_c2_1
      DEBUG_API_USER: "admin"
      DEBUG_API_PASSWORD: "password123"
      DEBUG_API_ADDR: "0.0.0.0:8080"
    ports:
      - "127.0.0.1:8080:8080"

  c2:
    build:
      context: ../
      dockerfile: "./docker/c2.Dockerfile"
      target: production
    environment:
      HTTP_ADDR: "0.0.0.0:80"
      TEAMSERVER_URL: "http://paragon_teamserver_1/graphql"

  teamserver:
    build:
      context: ../
      dockerfile: "./docker/teamserver.Dockerfile"
      target: production
    environment:
      HTTP_ADDR: "0.0.0.0:80"
    ports:
      - "127.0.0.1:80:80"