name: Review Dog
on: [pull_request]
jobs:
    reviewdog-pr:
        if: github.event_name == 'pull_request'
        name: Review Dog (Pull Request)
        runs-on: ubuntu-latest
        steps:
          - uses: actions/setup-go@v1
            with:
              go-version: 1.14

          - name: Add $GOPATH/bin
            run: |
              echo ::add-path::$(go env GOPATH)/bin
          - uses: actions/checkout@v2

          # https://github.com/actions/cache/blob/master/examples.md#go---modules
          - name: Cache Go Modules
            id: cache
            uses: actions/cache@v1
            with:
              path: ~/go/pkg/mod
              key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
              restore-keys: |
                ${{ runner.os }}-go-
          - name: Download Go Modules
            if: steps.cache.outputs.cache-hit != 'true'
            run: go mod download

          - name: Install linters
            run: '( cd linters && go get golang.org/x/lint/golint )'

          - name: Setup reviewdog
            run: |
              # mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
              # echo ::add-path::$HOME/bin
              go install ./cmd/reviewdog
          - name: Run reviewdog (github-pr-check)
            continue-on-error: true
            env:
              REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              reviewdog -reporter=github-pr-check -runners=golint,govet
          - name: Run reviewdog (github-pr-review with tee)
            env:
              REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              # Remove Go Problem Matchers [1] as it reports duplicate results with
              # reviewdog.
              # [1]: https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers
              echo "::remove-matcher owner=go::"
              golint ./... | reviewdog -f=golint -name=golint-pr-review -reporter=github-pr-review -tee



  reviewdog:
    name: Review Dog
    runs-on: ubuntu-latest
    steps:
      # ...
      - name: Setup Review Dog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
          echo ::add-path::$(go env GOPATH)/bin # for Go projects
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-check -runners=golint,govet
          # or
          reviewdog -reporter=github-pr-review -runners=golint,govet
